export const images = [
  {
    id: 1,
    image: "/assets/image1.png",
  },
  {
    id: 2,
    image: "/assets/image2.jpg",
  },
  {
    id: 3,
    image: "/assets/image3.jpg",
  },
];

export const featuredProducts = [
  {
    id: 1,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 2,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 3,
    image: "/assets/dark1.jpg",
  },
  {
    id: 4,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 5,
    image: "/assets/pebbles.jpg",
  },
  {
    id: 6,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 7,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 8,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 9,
    image: "/assets/handmade.jpg",
  },
  {
    id: 10,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 11,
    image: "/assets/100g.jpg",
  },
  {
    id: 12,
    image: "/assets/1-2-chocolate-png-2.png",
  },
];

export const products = [
  {
    id: 1,
    image: "/assets/dark1.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 2,
    image: "/assets/dark2.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 3,
    image: "/assets/dark3.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 4,
    image: "/assets/100g.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 5,
    image: "/assets/50g.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 6,
    image: "/assets/20g.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 7,
    image: "/assets/nutty.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 8,
    image: "/assets/pebbles.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 9,
    image: "/assets/handmade.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
  },
  {
    id: 10,
    image: "/assets/royale.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.5,
    oldPrice: 90.0,
  },
  {
    id: 11,
    image: "/assets/alltime.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.55,
    oldPrice: 90.0,
  },
  {
    id: 12,
    image: "/assets/dark2.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.78,
    oldPrice: 90.0,
  },
];

export const rows = [
  {
    id: 1,
    product: "Kingsbite",
    img: "/assets/50g.jpg",
    size: "100g",
    flavour: "Milk",
    quantity: 1,
    price: 60.89,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 2,
    product: "Oranco",
    img: "/assets/50g.jpg",
    size: "50g",
    flavour: "dark",
    quantity: 3,
    price: 65.52,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 3,
    product: "Akuafo",
    img: "/assets/50g.jpg",
    size: "20g",
    flavour: "Milk",
    quantity: 10,
    price: 80.29,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 4,
    product: "Alltime",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Coffee",
    quantity: 5,
    price: 100.0,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 5,
    product: "Royale",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Raw",
    quantity: 2,
    price: 40.0,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 6,
    product: "Kingsbite",
    img: "/assets/50g.jpg",
    size: "100g",
    flavour: "Milk",
    quantity: 1,
    price: 60.89,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 7,
    product: "Oranco",
    img: "/assets/50g.jpg",
    size: "50g",
    flavour: "dark",
    quantity: 3,
    price: 65.52,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 8,
    product: "Akuafo",
    img: "/assets/50g.jpg",
    size: "20g",
    flavour: "Milk",
    quantity: 10,
    price: 80.29,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 9,
    product: "Alltime",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Coffee",
    quantity: 5,
    price: 100.0,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 10,
    product: "Royale",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Raw",
    quantity: 2,
    price: 40.0,
    date: "12th May,21",
    status: "in stock",
  },
];
