export const users = [
  {
    id: 1,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 2,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 3,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 4,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 5,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 6,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 7,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 8,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 9,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
  {
    id: 10,
    username: "Snow",
    avatar: "",
    email: "Joey@gmail.com",
    status: "active",
    transaction: "$120.00",
  },
];

export const images = [
  {
    id: 1,
    image: "/assets/image1.png",
  },
  {
    id: 2,
    image: "/assets/image2.jpg",
  },
  {
    id: 3,
    image: "/assets/image3.jpg",
  },
];

export const featuredProducts = [
  {
    id: 1,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 2,
    image: "/assets/20g.jpg",
  },
  {
    id: 3,
    image: "/assets/dark1.jpg",
  },
  {
    id: 4,
    image: "/assets/50g.jpg",
  },
  {
    id: 5,
    image: "/assets/pebbles.jpg",
  },
  {
    id: 6,
    image: "/assets/100g.jpg",
  },
  {
    id: 7,
    image: "/assets/1-2-chocolate-png-2.png",
  },
  {
    id: 8,
    image: "/assets/handmade.jpg",
  },
];

export const products = [
  {
    id: 1,
    image: "/assets/dark1.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 2,
    image: "/assets/dark2.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "passive",
  },
  {
    id: 3,
    image: "/assets/dark3.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 4,
    image: "/assets/100g.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "passive",
  },
  {
    id: 5,
    image: "/assets/50g.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 6,
    image: "/assets/20g.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 7,
    image: "/assets/nutty.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 8,
    image: "/assets/pebbles.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "passive",
  },
  {
    id: 9,
    image: "/assets/handmade.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.0,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 10,
    image: "/assets/royale.jpg",
    title: "TQ Premium 90%",
    newPrice: 60.5,
    oldPrice: 90.0,
    stock: 60,
    status: "passive",
  },
  {
    id: 11,
    image: "/assets/alltime.jpg",
    title: "TQ Premium 80%",
    newPrice: 60.55,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
  {
    id: 12,
    image: "/assets/dark2.jpg",
    title: "TQ Premium 70%",
    newPrice: 60.78,
    oldPrice: 90.0,
    stock: 60,
    status: "active",
  },
];

export const rows = [
  {
    id: 1,
    product: "Kingsbite",
    img: "/assets/50g.jpg",
    size: "100g",
    flavour: "Milk",
    quantity: 1,
    price: 60.89,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 2,
    product: "Oranco",
    img: "/assets/50g.jpg",
    size: "50g",
    flavour: "dark",
    quantity: 3,
    price: 65.52,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 3,
    product: "Akuafo",
    img: "/assets/50g.jpg",
    size: "20g",
    flavour: "Milk",
    quantity: 10,
    price: 80.29,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 4,
    product: "Alltime",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Coffee",
    quantity: 5,
    price: 100.0,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 5,
    product: "Royale",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Raw",
    quantity: 2,
    price: 40.0,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 6,
    product: "Kingsbite",
    img: "/assets/50g.jpg",
    size: "100g",
    flavour: "Milk",
    quantity: 1,
    price: 60.89,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 7,
    product: "Oranco",
    img: "/assets/50g.jpg",
    size: "50g",
    flavour: "dark",
    quantity: 3,
    price: 65.52,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 8,
    product: "Akuafo",
    img: "/assets/50g.jpg",
    size: "20g",
    flavour: "Milk",
    quantity: 10,
    price: 80.29,
    date: "12th May,21",
    status: "in stock",
  },
  {
    id: 9,
    product: "Alltime",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Coffee",
    quantity: 5,
    price: 100.0,
    date: "12th May,21",
    status: "Out of stock",
  },
  {
    id: 10,
    product: "Royale",
    img: "/assets/50g.jpg",
    size: "400g",
    flavour: "Raw",
    quantity: 2,
    price: 40.0,
    date: "12th May,21",
    status: "in stock",
  },
];

export const userData = [
  {
    name: "Jan",
    "Active Users": 1000,
  },

  {
    name: "Feb",
    "Active Users": 1300,
  },

  {
    name: "Mar",
    "Active Users": 1700,
  },

  {
    name: "Apr",
    "Active Users": 2000,
  },

  {
    name: "May",
    "Active Users": 3000,
  },

  {
    name: "Jun",
    "Active Users": 1000,
  },

  {
    name: "Jul",
    "Active Users": 2800,
  },

  {
    name: "Aug",
    "Active Users": 4000,
  },

  {
    name: "Sept",
    "Active Users": 3000,
  },

  {
    name: "Oct",
    "Active Users": 3500,
  },

  {
    name: "Nov",
    "Active Users": 300,
  },

  {
    name: "Dec",
    "Active Users": 4000,
  },
];

export const latestTransaction = [
  {
    id: 1,
    customer: "Rose Peprah",
    date: "12 Feb 2022",
    amount: 600,
    summary: "Paid",
    img: "",
  },
  {
    id: 2,
    customer: "Joey Tsino",
    date: "15 Jan 2022",
    amount: 200,
    summary: "Paid",
    img: "",
  },
  {
    id: 3,
    customer: "Anderson Aloko",
    date: "9 Jan 2022",
    amount: 600,
    summary: "Paid",
    img: "",
  },
  {
    id: 4,
    customer: "Francis Mahdi",
    date: "06 Jan 2022",
    amount: 400,
    summary: "Paid",
    img: "",
  },
  {
    id: 5,
    customer: "Junior Francis",
    date: "1 Feb 2022",
    amount: 800,
    summary: "Paid",
    img: "",
  },
];

export const order = [
  {
    id: 1,
    products: [
      {
        productName: "Kingsbite",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Oranco",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Dark Chocolate",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
    ],
    fullName: "Joey Tsino",
    subtotal: 500,
    delivery: 30,
    total: 600,
    phone: "0202335987",
    email: "tsy@gmail.com",
    region: "Greater Accra",
    city: "Tema",
    apartmentSuite: "123 Bolevan",
    status: "Fullfilled",
    instruction: "Please handle with care",
  },
  {
    id: 2,
    products: [
      {
        productName: "Kingsbite",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Oranco",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Dark Chocolate",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
    ],
    fullName: "Joey patsi",
    subtotal: 500,
    delivery: 30,
    total: 700,
    phone: "0202335987",
    email: "tsy@gmail.com",
    region: "Greater Accra",
    city: "Tema",
    apartmentSuite: "123 Bolevan",
    status: "Pending",
    instruction: "",
  },
  {
    id: 3,
    products: [
      {
        productName: "Kingsbite",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Oranco",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Dark Chocolate",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
    ],
    fullName: "Joey Putnum",
    subtotal: 500,
    delivery: 30,
    total: 650,
    phone: "0202335987",
    email: "tsy@gmail.com",
    region: "Greater Accra",
    city: "Tema",
    apartmentSuite: "123 Bolevan",
    status: "Pending",
    instruction: "",
  },
  {
    id: 4,
    products: [
      {
        productName: "Kingsbite",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Oranco",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Dark Chocolate",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
    ],
    fullName: "Joey Tsino",
    subtotal: 500,
    delivery: 30,
    total: 600,
    phone: "0202335987",
    email: "tsy@gmail.com",
    region: "Greater Accra",
    city: "Tema",
    apartmentSuite: "123 Bolevan",
    status: "Fullfilled",
    instruction: "Please handle with care",
  },
  {
    id: 5,
    products: [
      {
        productName: "Kingsbite",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Oranco",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
      {
        productName: "Dark Chocolate",
        quantity: 3,
        price: 60,
        size: "100g",
        amount: 180,
      },
    ],
    fullName: "Joey Tsino",
    subtotal: 500,
    delivery: 30,
    total: 700,
    phone: "0202335987",
    email: "tsy@gmail.com",
    region: "Greater Accra",
    city: "Tema",
    apartmentSuite: "123 Bolevan",
    status: "Pending",
    instruction: "",
  },
];
